default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: doctello_development

test:
  <<: *default
  database: doctello_test

production:
  <<: *default
  database: doctello_production
