development:
  secret_key_base: super_long_secret_key_for_development
  active_merchant_login: 896667
  active_merchant_password: supersecretpassword888

test:
  secret_key_base: super_long_secret_key_for_test
  active_merchant_login: 896667
  active_merchant_password: supersecretpassword888

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  active_merchant_login: <%= ENV["AM_LOGIN"] %>
  active_merchant_password: <%= ENV["AM_PASSWORD"] %>
